[package]
name = "nablo_programe"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
env_logger = "0.11.3"
lazy_static = "1.5.0"
log = "0.4.22"
pest = "2.7.11"
pest_derive = "2.7.11"
rayon = "1.10.0"
# thiserror = "1.0.61"
